import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar";
import FriendsTab from "../components/FriendsTab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Y - Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="flex h-screen">
          <div className="w-1/4 p-4 border-r border-gray-800">
            <Navbar />
          </div>
          <div className="w-2/4 p-4 ">{children}</div>
          <div className="w-1/4 p-4 border-l border-gray-800">
            <FriendsTab />
          </div>
        </div>
      </body>
    </html>
  );
}
