import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Head from 'next/head'
import FriendsTab from './components/FriendsTab'
import PostDIv from './components/PostDIv'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div >
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=optional" rel="stylesheet" />
      </Head>
      <div className='flex h-screen'>
        <Navbar />
        <PostDIv/>
        <FriendsTab/>
      </div>
      
      <main >{children}</main>
    </div>
  )
}
