import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Y - Social Network',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
     <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        
      </Head>
      <body >{children}</body>
    </html>
  )
}
