import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "./components/Navbar";
import FriendsTab from "./components/FriendsTab";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Y - Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <div className="flex h-screen bg-[#000e24]">
        <div className="w-1/4 p-4 border-r-2 border-gray-900">
          <Navbar />
        </div>
        <div className="w-2/4 p-4">
          <main >{children}</main>
        </div>
        <div className="w-1/4 p-4 border-l-2 border-gray-900">
          <FriendsTab />
        </div>

        
      </div>
    </html>
  );
}
